### ISSUE TITLE
sample_new_textures demo can't open SMPLX pkl

### ISSUE THREAD

**Issue by jaymefosa** [saic-vul/style-people#3]
File "/home/jayme/anaconda3/envs/hsnet/lib/python3.7/site-packages/numpy/lib/npyio.py", line 460, in load
    return pickle.load(fid, **pickle_kwargs)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 0: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample_new_textures.py", line 30, in <module>
    inferer = DemoInferer(args.checkpoint_path, args.smplx_model_dir, imsize=args.imsize, device=args.device)
  File "/home/jayme/Projects/Gist/style-people/utils/demo.py", line 67, in __init__
    self.smplx_models_dict = build_smplx_model_dict(smplx_model_dir, device)
  File "/home/jayme/Projects/Gist/style-people/utils/smplx_models.py", line 7, in build_smplx_model_dict
    gender2model = {k:smplx.body_models.SMPLX(v).to(device) for (k, v) in gender2path.items()}
  File "/home/jayme/Projects/Gist/style-people/utils/smplx_models.py", line 7, in <dictcomp>
    gender2model = {k:smplx.body_models.SMPLX(v).to(device) for (k, v) in gender2path.items()}
  File "/home/jayme/anaconda3/envs/hsnet/lib/python3.7/site-packages/smplx/body_models.py", line 953, in __init__
    model_data = np.load(smplx_path, allow_pickle=True)
  File "/home/jayme/anaconda3/envs/hsnet/lib/python3.7/site-packages/numpy/lib/npyio.py", line 463, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file 'data/smplx/SMPLX_NEUTRAL.pkl' as a pickle

**Comment by jaymefosa** [comment]
Changing a line in utils.smplx_models solved this:

`    gender2model = {k:smplx.body_models.SMPLX(v).to(device) for (k, v) in gender2path.items()}`

to

`    gender2model = {k:smplx.body_models.SMPLX(v, ext="pkl").to(device) for (k, v) in gender2path.items()}`
